# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  projs: '**/*.csproj'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 3.0'
  inputs:
    packageType: sdk
    version: '3.0.100-rc1-014190'

- task: DotNetCoreCLI@2
  displayName: 'Restore projects'
  inputs:
    projects: '$(projs)'
    command: restore

- task: DotNetCoreCLI@2
  displayName: 'Build all projects'
  inputs:
    projects: '$(projs)'
    command: build
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    projects: 'Berrysoft.XXTea.Test/Berrysoft.XXTea.Test.csproj'
    command: test
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Pack Berrysoft.XXTea'
  inputs:
    projects: 'Berrysoft.XXTea/Berrysoft.XXTea.csproj'
    command: pack
    configurationToPack: '$(buildConfiguration)'
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish'
  inputs:
    artifactName: 'NuGet'
